"""Lifts Table

Revision ID: 45f7b0cd2672
Revises: 4d7ab5ecbb81
Create Date: 2024-09-08 22:26:24.553430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f7b0cd2672'
down_revision = '4d7ab5ecbb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifts_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lift_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_lifts_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lifts_table')
    # ### end Alembic commands ###
