"""init

Revision ID: 968ffe3a04d8
Revises: 
Create Date: 2024-09-26 23:37:53.542006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968ffe3a04d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('lifts_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lift_name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_lifts_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=False),
    sa.Column('meal_plan', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_meals_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('current_weight', sa.Float(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=False),
    sa.Column('workout_plan', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_workouts_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workouts_table')
    op.drop_table('meals_table')
    op.drop_table('lifts_table')
    op.drop_table('users_table')
    # ### end Alembic commands ###
